
.. _blobstore-cookbook:

BlobStore Recipes
-----------------

Recipes for working with Predix Python SDK and the Blob Store service.

It is expected you used the SDK to create the service so that it is configured
by Manifest.

How-To Interface with Blob Store
................................

Blob Store can only be used from within the Cloud Foundry environment.  In
order to upload images from the Edge you may need a sample app like the
following demonstration.

https://github.com/j12y/predix-flask-blobstore

