
App Manifest
------------

The App Manifest is an approach to configuring your application for deployment
to platforms based on Cloud Foundry such as Predix.  The Administration Apps
allow you to automate the management of your space through the creation of
services with a side-effect of generating a manifest configuration file.

The mechanics of this are described in the Getting Started section.

App Manifest API
................

.. automodule:: predix.app
    :members:

Admin App Manifest API
......................

.. automodule:: predix.admin.app
    :members:

